version: "3.8"

services:
  # db:
  #   iamge: postgres:15.3
  #   stdin_open: true
  #   tty: true

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   stdin_open: true
  #   tty: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./roydy:/var/opt/roydy
    command: /bin/bash -c "npm run build-css & dx serve --hot-reload"
    ports:
      - "8080:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true
